"""
Profit & Loss Statement Generator — auto-generates P&L from transactions.
Tabby has basic P&L. Ours has full IRS-aligned breakdown.
"""

from datetime import datetime


def generate_pnl(categorized_transactions, period_name=''):
    """Generate Profit & Loss statement from categorized transactions."""

    income_categories = ['income']
    expense_categories = [
        'advertising', 'car_transport', 'insurance', 'office_supplies',
        'software_subscriptions', 'professional_services', 'meals_entertainment',
        'education_training', 'rent_office', 'phone_internet', 'bank_fees',
        'equipment', 'personal',
    ]

    # Calculate totals
    income_items = {}
    expense_items = {}
    total_income = 0
    total_expenses = 0
    total_deductible = 0

    for txn in categorized_transactions:
        cat = txn.get('category', 'uncategorized')
        amount = abs(txn.get('amount', 0))
        ded = txn.get('deductible_amount', 0)

        if cat in income_categories or txn.get('amount', 0) > 0:
            if cat not in income_items:
                income_items[cat] = {'total': 0, 'count': 0}
            income_items[cat]['total'] += amount
            income_items[cat]['count'] += 1
            total_income += amount
        elif cat not in ('transfer',):
            if cat not in expense_items:
                expense_items[cat] = {'total': 0, 'count': 0, 'deductible': 0}
            expense_items[cat]['total'] += amount
            expense_items[cat]['count'] += 1
            expense_items[cat]['deductible'] += ded
            total_expenses += amount
            total_deductible += ded

    net_profit = total_income - total_expenses
    profit_margin = (net_profit / total_income * 100) if total_income > 0 else 0

    # Monthly breakdown
    monthly = {}
    for txn in categorized_transactions:
        date_str = str(txn.get('date', ''))[:7]
        if date_str not in monthly:
            monthly[date_str] = {'income': 0, 'expenses': 0}
        if txn.get('category') in income_categories or txn.get('amount', 0) > 0:
            monthly[date_str]['income'] += abs(txn.get('amount', 0))
        elif txn.get('category') != 'transfer':
            monthly[date_str]['expenses'] += abs(txn.get('amount', 0))

    # Build P&L text
    if not period_name:
        dates = [txn.get('date', '') for txn in categorized_transactions if txn.get('date')]
        period_name = f"{min(dates)} to {max(dates)}" if dates else 'Current Period'

    lines = []
    lines.append("=" * 60)
    lines.append(f"  PROFIT & LOSS STATEMENT")
    lines.append(f"  BooksBird AI — {period_name}")
    lines.append(f"  Generated: {datetime.now().strftime('%B %d, %Y')}")
    lines.append("=" * 60)

    lines.append("\n  REVENUE")
    lines.append("  " + "-" * 50)
    for cat, info in sorted(income_items.items(), key=lambda x: x[1]['total'], reverse=True):
        name = cat.replace('_', ' ').title()
        lines.append(f"    {name:35s}  ${info['total']:>12,.2f}")
    lines.append("  " + "-" * 50)
    lines.append(f"    {'TOTAL REVENUE':35s}  ${total_income:>12,.2f}")

    lines.append("\n  EXPENSES (Tax Deductible)")
    lines.append("  " + "-" * 50)
    for cat, info in sorted(expense_items.items(), key=lambda x: x[1]['total'], reverse=True):
        if info.get('deductible', 0) > 0:
            name = cat.replace('_', ' ').title()
            lines.append(f"    {name:35s}  ${info['total']:>12,.2f}  (ded: ${info['deductible']:,.2f})")

    lines.append("\n  EXPENSES (Non-Deductible)")
    lines.append("  " + "-" * 50)
    for cat, info in sorted(expense_items.items(), key=lambda x: x[1]['total'], reverse=True):
        if info.get('deductible', 0) == 0:
            name = cat.replace('_', ' ').title()
            lines.append(f"    {name:35s}  ${info['total']:>12,.2f}")

    lines.append("\n  " + "-" * 50)
    lines.append(f"    {'TOTAL EXPENSES':35s}  ${total_expenses:>12,.2f}")
    lines.append(f"    {'TOTAL DEDUCTIBLE':35s}  ${total_deductible:>12,.2f}")

    lines.append("\n  " + "=" * 50)
    lines.append(f"    {'NET PROFIT':35s}  ${net_profit:>12,.2f}")
    lines.append(f"    {'PROFIT MARGIN':35s}  {profit_margin:>11.1f}%")
    lines.append("  " + "=" * 50)

    lines.append("\n  MONTHLY TREND")
    lines.append("  " + "-" * 50)
    for month in sorted(monthly.keys()):
        m = monthly[month]
        profit = m['income'] - m['expenses']
        bar = "█" * min(int(profit / max(net_profit, 1) * 20), 20) if profit > 0 else ""
        lines.append(f"    {month}  In:${m['income']:>8,.0f}  Ex:${m['expenses']:>8,.0f}  P:${profit:>8,.0f}  {bar}")

    lines.append("\n  " + "-" * 50)
    lines.append("  Generated by BooksBird AI | Not financial advice")

    return {
        'text': '\n'.join(lines),
        'total_income': total_income,
        'total_expenses': total_expenses,
        'net_profit': net_profit,
        'profit_margin': round(profit_margin, 1),
        'total_deductible': total_deductible,
        'income_breakdown': income_items,
        'expense_breakdown': expense_items,
        'monthly': monthly,
    }
